name: athlete_hub_backend
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^2.5.2
  path_provider: ^2.1.1
 
  file_picker: ^6.1.1  # Add this
  
  shelf_multipart: ^1.0.0



  path: ^1.8.0